### ISSUE TITLE
MKArmageddon - Kreate A Fighter

### ISSUE THREAD

**Issue by 972oTeV** [leeao/MortalKombat#1]
Hi again! 😄 

The script works very nice 💯 with all the models i tested, but i'm here for the Faces from the Kreate a Fighter - MKA.
The diferent bodies, and parts (i don't try every one yet, but some of them yes) loads good, but when i try to open the faces:
![error](https://github.com/leeao/MortalKombat/assets/122237320/1b0a8c4b-790c-47f9-b8e4-01b4a47df900)

and that's the problem, here the samples: https://mega.nz/file/NkwWzTYb#vvP-WIuWBGSddAw63QYyHeSB8R6ShtninRO0gW1TH4w 
extracted with the Ermaccer's tool.

And another question: 
What about Shaolin Monks? There are someone working on some tool for that? What's the problem of that game? i mean, no one can obtain anything (3D) from there. Why? Did you know? 😕 

And that's all, hope you are Fine. 
See ya 👍

**Comment by leeao** [comment]
Hi, they are morph targets deformation models.
I have fixed it, please check for updates.
![MorphTargets](https://github.com/leeao/MortalKombat/assets/15622541/d314fdef-c42a-4cbe-8a12-eb53636e6c41)
The dff model in Male Faces is an empty file, and there is no content in it, all of which is 00 data.

Researching the MK model was purely accidental, as a series of coincidences led me to encounter some games with the Renderware engine. For example, I accepted a friend's request to research "Silent Hill: Origins" and "Evil Dead Regeneration". So I am more interested in RW games.
I have privately researched over a dozen RW games. Including PC, XBOX, PSP, PS2, WII platforms.

Ermaccer told me that MK is also an RW engine, so I researched it.
Shaolin Monks is unsure of its engine and currently has no plans as I do not have more time on other projects. Recently, I am working on writing a DFF Blender exporter for MK PS2.

**Comment by 972oTeV** [comment]
Thanks @leeao, i will check the new update, sorry for bother 
Weird about the male faces, i have to search more 😄 👍 

And about the MK SM, it's ok, no problem 😃 
because th game it's from those years, everyone think was made with RW, but it's a curious game.

Thanks again 💯 

--------------------------------

Edit:
i check another female faces, and works, but i extracted the male faces with a new version of ermaccer tool, and now i have this text:
![males](https://github.com/leeao/MortalKombat/assets/122237320/ffc3d0ce-7e43-42e9-9dc3-f93ed7eadcef)

Files: https://mega.nz/file/o4JQwQ7L#zWFd8CqOy4E-DWEDcj7wVIHONrO63SrbqH5MRlwFNAg

**Comment by leeao** [comment]
Hi, Fixed.
Check update again.
