### ISSUE TITLE
Stage issue

### ISSUE THREAD

**Issue by 972oTeV** [leeao/MortalKombat#2]
Hi again! 
Sorry for bother (Again)

Well, 
This time i tried to open (or directly convert) the stage "Lava shrine" from MKDA, and noesis Crashes 
(only with that stage from MKDA, i didn't test stages from MKD or MKA Yet)
![error stage2](https://github.com/leeao/MortalKombat/assets/122237320/8ac44196-4d6f-4d49-8b1d-7d88aceccb5c)

BUT!
i have another old noesis, with the previous version of the Script (the one before the morph update) 
and this is the error, maybe can Help:
![error stage](https://github.com/leeao/MortalKombat/assets/122237320/813334fe-5122-4084-9e1f-ff36d0667595)

I test with different version of ermaccer tool, and different noesis (the one of the error screenshot isn't the one i use), 
and the same crash.

Here's the samples:
https://mega.nz/file/t4gChDDZ#pUTcX69lNVO9urxrvsJxqMVnyyaqaOFQNNr-D1MOl3M 
(The files outside of the folder were extracted with differents version of ermaccer tool)

Thanks in advance! 😃

**Comment by leeao** [comment]
The stage model contains a morph target model, but an error occurred during model construction, so support for the morph target has been removed.
